source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'sprockets-rails', :require => 'sprockets/railtie'
gem 'bootstrap', '~> 4.0.0.alpha3.1'
gem 'devise', '~> 4.2'
gem 'devise_invitable', '~> 1.7'
gem 'apartment', '~> 1.2'
gem 'simple_form', '~> 3.2', '>= 3.2.1'
gem 'font-awesome-rails', '~> 4.6', '>= 4.6.3.1'
gem 'country_select', '~> 2.5', '>= 2.5.2'
gem 'quickbooks-ruby', '~> 0.4.4'
gem 'quickbooks-ruby-base', '~> 1.6'
gem 'qbo_rails', git: 'git://github.com/minimul/qbo_rails.git'
gem 'oauth-plugin', '~> 0.5.1'
gem 'dotenv-rails', '~> 2.1', '>= 2.1.1'
gem 'cocoon', '~> 1.2', '>= 1.2.9'
gem 'local_time', '~> 1.0', '>= 1.0.3'
gem 'will_paginate', '~> 3.1'
gem 'goldiloader'
gem 'slim', '~> 3.0', '>= 3.0.7'
gem 'slim-rails', '~> 3.1'
gem 'peddler', '~> 1.4'
gem 'client_side_validations',
     github: 'DavyJonesLocker/client_side_validations',
     branch: 'rails5'
gem 'client_side_validations-simple_form',
     github: 'DavyJonesLocker/client_side_validations-simple_form',
     branch: 'rails5'

group :development, :test do
  gem 'guard', '~> 2.14'
  gem 'guard-livereload', '~> 2.5', '>= 2.5.2'
  gem 'guard-rspec', '~> 4.7', '>= 4.7.3'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.1'
  gem 'capybara', '~> 2.7', '>= 2.7.1'
  gem 'factory_girl_rails', '~> 4.7'
  gem 'database_cleaner', '~> 1.5', '>= 1.5.3'
  gem 'shoulda-matchers', '~> 3.1', '>= 3.1.1'
  gem 'letter_opener', '~> 1.4', '>= 1.4.1'
  gem 'email_spec', '~> 2.1'
  gem 'capybara-webkit', '~> 1.11', '>= 1.11.1'
  gem 'selenium-webdriver', '~> 2.53', '>= 2.53.4'
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry'
  gem 'pry-rails'
  gem 'better_errors', '~> 2.1', '>= 2.1.1'
  gem 'bullet', '~> 5.3'
end
